# Generated by Django 4.2.4 on 2023-09-14 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='ФИО')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('last_pos', models.CharField(blank=True, max_length=100, null=True)),
                ('last_post_date_time', models.DateTimeField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Logist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Логист',
                'verbose_name_plural': 'Логисты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('plan_date', models.CharField(max_length=256)),
                ('date_logist', models.CharField(max_length=256)),
                ('qu', models.CharField(max_length=256)),
                ('sqr', models.CharField(max_length=256)),
                ('transportinfo', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=256)),
                ('floor', models.CharField(max_length=256)),
                ('c_name', models.CharField(max_length=256)),
                ('s_name', models.CharField(max_length=256)),
                ('crew', models.CharField(max_length=256)),
                ('manager', models.CharField(max_length=256)),
                ('calc_manager', models.CharField(max_length=256)),
                ('delivery_sum', models.CharField(max_length=256)),
                ('delivery_time', models.CharField(max_length=256)),
                ('pos', models.CharField(max_length=60)),
                ('response', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_link', models.URLField(max_length=1000)),
                ('is_finish', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.logist', verbose_name='Логист')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver', verbose_name='Водитель')),
                ('orders', models.ManyToManyField(to='core.order')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='response/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
    ]
