# Generated by Django 4.2.3 on 2023-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('plan_date', models.CharField(blank=True, max_length=100, null=True)),
                ('change_date', models.CharField(blank=True, max_length=100, null=True)),
                ('qu', models.CharField(blank=True, max_length=100, null=True)),
                ('sqr', models.CharField(blank=True, max_length=100, null=True)),
                ('transportinfo', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('s_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='address',
        ),
        migrations.RemoveField(
            model_name='route',
            name='c_name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='route',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='route',
            name='o_name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='route',
            name='plan_date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='qu',
        ),
        migrations.RemoveField(
            model_name='route',
            name='s_name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='sqr',
        ),
        migrations.RemoveField(
            model_name='route',
            name='transportinfo',
        ),
        migrations.AddField(
            model_name='route',
            name='orders',
            field=models.ManyToManyField(to='core.order'),
        ),
    ]
