# Generated by Django 4.2.4 on 2023-08-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='change_date',
            new_name='date_logist',
        ),
    ]
