# Generated by Django 4.2.4 on 2023-08-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
