# Generated by Django 4.2.4 on 2023-08-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_route_is_loaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='genaral_sqr',
        ),
        migrations.RemoveField(
            model_name='route',
            name='last_address',
        ),
        migrations.RemoveField(
            model_name='route',
            name='last_address_pos',
        ),
    ]
