# Generated by Django 4.2.4 on 2023-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_route_genaral_sqr_remove_route_last_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
