# Generated by Django 4.2.4 on 2023-08-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_route_is_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='is_loaded',
        ),
    ]
