# Generated by Django 4.2.4 on 2023-08-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_response_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_link',
            field=models.URLField(max_length=1000),
        ),
    ]
